[pyprland]
plugins = [ "scratchpads", "fetch_client_menu" ]

[scratchpads.btop]
command = "alacritty --config-file /home/sinh/.config/bspwm/alacritty/alacritty.toml --class bashtop,bashtop --command btop"
position = "100px 100px"
size = "800px 800px"
class = "foot-btop"

[scratchpads.bitwarden]
command = "bitwarden"
position = "100px 100px"
size = "800px 800px"
class = "scratchpads"

# Somehow Caprine dosn't work with scratchpads always pop out and pyprland couldn't detect it
# [scratchpads.messenger]
# command = "caprine"
# position = "100px 100px"
# size = "800px 800px"
# class = "Caprine"

[scratchpads.viber]
command = "viber"
position = "100px 100px"
size = "800px 800px"
class = "viber"

