#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## launch terminal with alt config

CONFIG="/home/sinh/.config/hypr/foot/foot.ini"

if [ "$1" == "-f" ]; then
	foot --app-id='foot-float' --config="$CONFIG"
elif [ "$1" == "-F" ]; then
	foot --fullscreen --app-id='foot-full' --font="Iosevka Nerd Font:size=14" --override=pad=35x35 --config="$CONFIG"
else
	foot --config="$CONFIG"
fi
