#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Autostart Programs

# Kill already running process
# _ps=(waybar mako)
# for _prs in "${_ps[@]}"; do
# 	if [[ `pidof ${_prs}` ]]; then
# 		killall -9 ${_prs}
# 	fi
# done

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# set wallpaper
# /home/sinh/.config/hypr/scripts/wallpaper &
swww-daemon
swww img /home/sinh/pictures/wallpapers/wallhaven-4d9e93-3840x2400.jpg

# apply themes
# /home/sinh/.config/hypr/scripts/gtkthemes &

# lauch notification daemon (mako)
/home/sinh/.config/hypr/scripts/notifications &

# start network manager applet

# start mpd
exec mpd &

# utilities
copyq &
fcitx5 &
